services:
  # Servicio de la Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine 
    container_name: postgres_db_nube
    volumes:
      # Named volume
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # le pasamos las variables de .env
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - nube_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5 

  # Servicio de la API de Django
  web:
    container_name: django_web_nube
    build:
      context: ./backend # ubicación del Dockerfile
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # Bind mount
      - ./backend:/app
    ports:
      - "8000:8000" 
    env_file:
      - .env
    environment:
      - DB_HOST=db 
    depends_on:
       db:
         condition: service_healthy 
    networks:
      - nube_network

# Volúmenes y redes
volumes:
  postgres_data:

networks:
  nube_network:
    driver: bridge